<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BitFaster.Caching" Version="2.5.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="ParquetSharp" Version="21.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OSWS.Models\OSWS.Models.csproj" />
    <ProjectReference Include="..\OSWS.Common\OSWS.Common.csproj" />
  </ItemGroup>
</Project>
